version: 2
ethernets:
    eth0:
        dhcp4: false
        dhcp6: false
        addresses: [ "${mgmt_ip}/${netmask}" ]
        gateway4: ${gateway}
        nameservers:
           addresses: [ "${nameserver}" ]
    eth1:
        dhcp4: false
        dhcp6: false
        addresses: [ "${core1_ip}/${netmask}" ]
        routes:
            - to: "${edge1_wan1_ip}"
              via: "${core1_gateway}"
            - to: "${edge2_wan1_ip}"
              via: "${core1_gateway}"
    eth2:
        dhcp4: false
        dhcp6: false
        addresses: [ "${core2_ip}/${netmask}" ]
        routes:
            - to: "${edge1_wan2_ip}"
              via: "${core2_gateway}"
            - to: "${edge2_wan2_ip}"
              via: "${core2_gateway}"
 