#cloud-config
hostname: ${hostname}
manage_etc_hosts: true
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
disable_root: false
ssh_pwauth: true
chpasswd:
   expire: False
   list: |
      ubuntu:flexiwan

runcmd:
  - sudo chown ubuntu:ubuntu /etc/sysctl.conf
  - sudo echo net.ipv6.conf.all.disable_ipv6=1 >> /etc/sysctl.conf
  - sudo echo net.ipv6.conf.default.disable_ipv6=1 >> /etc/sysctl.conf
  - sudo echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf
  - sudo sysctl -p
