version: 2
ethernets:
    eth0:
        dhcp4: false
        dhcp6: false
        addresses: [ "${mgmt_ip}/${netmask}" ]
    eth1:
        dhcp4: false
        dhcp6: false
        addresses: [ "${core1_ip}/${netmask}" ]
        gateway4: ${gateway}
        nameservers:
          addresses: [ "${nameserver}" ]
    eth2:
        dhcp4: false
        dhcp6: false
        addresses: [ "${edge1_wan1_ip}/${netmask}" ]
    eth3:
        dhcp4: false
        dhcp6: false
        addresses: [ "${edge2_wan1_ip}/${netmask}" ]
 
